---
- name: Cria banco de dados wordpress
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Cria usuario de banco para wordpress
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL
